config/routes.rb
Rails.application.routes.draw do
mount Attachinary::Engine => "/attachinary"

root to: 'pages#home'

resources :collections, only: [:index] do
  resources :shoes, only: [:new, :create, :index, :show, :update]
end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collection.rb
class Collection < ApplicationRecord
  has_attachment :photo
  has_many :shoes
end

app/models/shoe.rb
class Shoe < ApplicationRecord
  has_attachments :photos
  belongs_to :collection
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  def index
    @collections = Collection.all
  end

  private

    def collection_params
      params.require(:collection).permit(:name, :description, :photo)
    end

  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController
   before_action :set_collection, only: [:new, :create, :index]
  def new
    @shoe = Shoe.new
  end

  def create
    @shoe = Shoe.new(shoe_params)
    @shoe.collection = @collection

    if @shoe.save
      redirect_to collection_shoes_path
    else
      render :new
    end
  end


  def index
    @shoes = @collection.shoes
  end

  def show
  end

 private

    def set_collection
      @collection = Collection.find(params[:collection_id])
    end

    def shoe_params
      params.require(:shoe).permit(:name, :description, :color, :size, :price, photos: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/views/collections/index.html.erb
<div class="collection-banner navbar-marged" style="background-image: linear-gradient(-225deg, rgba(186, 139, 2, 0.5) 0%, rgba(24,24,24,0.2) 50%), url(<%= asset_path('kandisky.jpg') %>);">
  <div class="collection-header-title">
    <h2 class="text-center">LA TRIBU #1</h2>
  </div>
</div>

<div class="container">
  <% @collections.each_with_index do |collection, i| %>
    <div class="row-fluid collection-grid">
      <% if i.even? %>
        <div class="col-sm-6 col-xs-12 collection-image" style="background-image: url('<%= cl_image_path collection.photo.path %>')">
          <img src='<%= cl_image_path collection.photo.path %>' class="img-responsive" style="visibility: hidden;"/>
        </div>
        <div class="col-sm-6 hidden-xs">
          <h4 class="collection-name"><%= collection.name %></h4>
          <p>-</p>
          <p class="collection-description"><%= collection.description %></p>
          <%= link_to collection_shoes_path(collection) do %>
            <h4 class="shoe-link">Découvrir ></h4>
          <% end %>
        </div>
      <% else %>
        <div class="col-sm-6 hidden-xs">
          <h4 class="collection-name"><%= collection.name %></h4>
          <p>-</p>
          <p class="collection-description"><%= collection.description %></p>
          <%= link_to collection_shoes_path(collection.id) do %>
            <h4 class="shoe-link">Découvrir ></h4>
          <% end %>
        </div>
        <div class="col-sm-6 col-xs-12 collection-image" style="background-image: url('<%= cl_image_path collection.photo.path %>')">
          <img src='<%= cl_image_path collection.photo.path %>' class="img-responsive" style="visibility: hidden;" />
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CΛVΛL</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= cloudinary_js_config %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg,   rgba(186, 139, 2, 0.5) 0%, rgba(24,24,24,0.6) 50%), url('http://www.tweakconsulting.com/wp-content/uploads/2015/09/Tweak-your-fear.jpg');">
  <div class="banner-content">
    <h1>CΛVΛL</h1>
    <p>Par-delà les évidences</p>
  <%= link_to collections_path do %>
    <h3 class="collection-link">Découvrez nos collections ></h3>
  <% end %>
  </div>

app/views/shared/_navbar.html.erb
<div class="navbar-caval navbar navbar-inverse opaque-navbar navbar-fixed-top">
  <%= link_to root_path do %><h2>CΛVΛL</h2><% end %>
  <%= link_to collections_path do %><h5>Collection</h5><% end %>
  <%= link_to root_path do %><h5>La marque</h5><% end %>
  <%= link_to root_path do %><h5>L'équipe</h5><% end %>
</div>

app/views/shoes/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-6 col-lg-offset-3">
      <h3 class="text-center">Ajout d'une chaussure à la collection <%= @collection.name %></h3>
      <%= simple_form_for [@collection, @shoe] do |f| %>
        <%= f.error_notification %>
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :size %>
        <%= f.input :price %>
        <%= f.input :color %>
        <%= f.input :photos, as: :attachinary %>
        <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/shoes/create.html.erb
<h1>Shoes#create</h1>
<p>Find me in app/views/shoes/create.html.erb</p>

app/views/shoes/index.html.erb
<div class="container navbar-marged">
  <h2 class="text-center"><%= @collection.name %></h2>
  <div class="row text-center">
    <% @shoes.each do |shoe| %>
      <div class="col-lg-4">
        <%= cl_image_tag shoe.photos[0].path, class: "img-responsive" %>
       <h3><%= shoe.name %></h3>
       <p><%= shoe.description %></p>
       <h4><%= shoe.price %></h4>
      </div>
    <% end %>
  </div>
</div>

app/views/shoes/new.html.erb
<%= render 'form' %>

app/views/shoes/show.html.erb
<h1>Shoes#show</h1>
<p>Find me in app/views/shoes/show.html.erb</p>